# Generated by Django 5.1.2 on 2024-11-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_calender_calendar_rename_teache_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Mentee',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Mentor',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='total_students',
            new_name='total_Mentees',
        ),
    ]
